### ISSUE TITLE
Everyone from every server joins the root channel.

### ISSUE THREAD

**Issue by deathspawn** [sm00th/bitlbee-discord#101] opened 2017-09-03 05:11 UTC
This is quite annoying as I am in a lot of servers and thus about 10,000+ people are sitting in &bitlbee. Is there a way to make it show just friends?

**Comment by sm00th** [comment] 2017-09-03 07:07
This is a duplicate of #89. While there is currently no way to only show friends there is a workaround to keep you userlists sane.

**Closed by sm00th** 2017-09-03 07:07 UTC
Labels: duplicate
