### ISSUE TITLE
Unable to join channels with the same channel name

### ISSUE THREAD

**Issue by Reusable-Box** [sm00th/bitlbee-discord#68] opened 2017-01-30 04:06 UTC
Hello,

I have several channels in my list with the default channel name of general. They all show up in the list of channels but, for example, my first channel named general is on index 9, then I have another channel named general on index 25, despite using the command to create a channel for index 25 when I join the channel it is the userlist/conversation for the channel on index 9.

**Comment by sm00th** [comment] 2017-01-30 07:39
This is a duplicate of #51 
There is a workaround: using `server_prefix_len` option, but I will look at this closer now that this bug is on master branch.

**Closed by sm00th** 2017-01-30 07:39 UTC
Labels: duplicate
