### ISSUE TITLE
chat list index out of order

### ISSUE THREAD

**Issue by parkerlreed** [sm00th/bitlbee-discord#70] opened 2017-02-05 08:46 UTC
For example mine starts out with 

````
<root> Index  Title                   Topic
<root>     1  developers              /r/googlehome/developers
<root>     2  mods                    /r/googlehome/mods
<root>     3  homeautomation          /r/googlehome/homeautomation
<root>     4  general                 The official chat room of https://www.reddit.com/r/googlehome/. Please connect to your Reddit account if possible.
<root>     5  mods                    steamlink/mods
<root>     6  support                 steamlink/support
<root>     7  general                 steamlink/general
````

But when I type `chat add discord !7 #steamlink` it maps to what is assigned to index 4 for some reason.

bitlbee 3.5.1-1
bitlbee-discord-git 146.3338ea7-1

**Comment by parkerlreed** [comment] 2017-02-05 09:17
Even after the order shifts (joined the bitlbee-discord server) it still joins the one hree before it (same channel as before)

````
<root> Index  Title                     Topic
<root>     1  the_one_you_shouldnt_see  But you do anyway because permissions do not work yet
<root>     2  testdump                  /ignore -channels #testdump *
<root>     3  beecord                   What else doesn't work yet?
<root>     4  developers                /r/googlehome/developers
<root>     5  mods                      /r/googlehome/mods
<root>     6  homeautomation            /r/googlehome/homeautomation
<root>     7  general                   The official chat room of https://www.reddit.com/r/googlehome/. Please connect to your Reddit account if possible.
<root>     8  mods                      steamlink/mods
<root>     9  support                   steamlink/support
<root>    10  general                   steamlink/general
````

**Comment by sm00th** [comment] 2017-02-05 10:02
This is a duplicate of #51. The workaround is to set server_prefix_len to non-zero.

**Comment by parkerlreed** [comment] 2017-02-05 10:15
Ahh thanks! Want me to close this out or leave it open?

**Comment by sm00th** [comment] 2017-02-05 10:33
I'll close it

**Closed by sm00th** 2017-02-05 10:33 UTC
Labels: duplicate
