### ISSUE TITLE
Channel removal causes undefined behaviour

### ISSUE THREAD

**Issue by Kays** [sm00th/bitlbee-discord#17] opened 2016-01-16 21:38 UTC
I think this is a followup to #14 

1. Create a new channel. I'll call it `#test` for reference.
2. Go to a different channel (let's say `#general`) and type something, referencing `#test` in a message in either/both Discord client and bitlbee-discord.
3. Delete the channel.
4. Type `#test` again in `#general` to verify that the links no longer work.
5. After that, messages that other people type in `#general` won't show up in bitlbee-discord. However, your messages sent from bitlbee-discord will still work.

P.S.: I'm still trying to figure another bug out that causes bitlbee to completely crash. When I was going through a few scenarios above while trying to find the culprit, I've triggered bitlbee to crash on many occasions but the steps to reproduce it is still unclear.

**Comment by sm00th** [comment] 2016-01-17 10:47
Yup, channel removal code left some structures behind that was leading to a lot of problems. I wasn't able to reproduce your exact case, but managed to get a "<#(null)>" in discord instead of non-linked removed channel name. The cause of all these issues(including your crash) should be the same and should be fixed in 2618d45. Can you please confirm that?

**Comment by sm00th** [comment] 2016-01-22 09:59
I assume it works now, if not - reopen this issue.

**Closed by sm00th** 2016-01-22 09:59 UTC
Labels: bug

**Comment by Kays** [comment] 2016-01-24 01:09
Confirmed; thank you!

My apologies for the delayed response. Busy week at work.
