### ISSUE TITLE
Unable to login with my account

### ISSUE THREAD

**Issue by madx** [sm00th/bitlbee-discord#4] opened 2015-12-08 07:11 UTC
Hello,

I can't login on Discord with the plugin since yesterday. I tried to upgrade bitlbee-discord with the latest changes but even after this I can't login. I get the following error:

```
discord - Login error: Failed to get server info.
discord - Logging in: Signing off..
discord - Logging in: Reconnecting in 5 seconds..
```

I am however able to login using the command line and mimicking what the `discord_http_login` is doing:

```
$ curl -X POST -d '{"email": "[REDACTED]", "password": "[REDACTED]"}' \
  -H "Content-Type: application/json" \
  -H "User-Agent: Bitlbee-Discord" \
  http://discordapp.com/api/auth/login

{"token": "[REDACTED]"}
```

**Comment by sm00th** [comment] 2015-12-08 08:48
"Failed to get server info" error was only present in nonwebsocket version when discord replied with a status code other than 200 after querying the user's list of "guilds".
Do you get any errors when trying to connect with latest version of the plugin? Is your account associated to any "guilds"?

**Comment by sm00th** [comment] 2015-12-27 16:46
Closing this as I can't reproduce this and it is reported against an old polling poc version.

**Closed by sm00th** 2015-12-27 16:46 UTC
